import 'package:elves_chatbot/presentation/widgets/Skeleton/skeletonbox.dart';
import 'package:elves_chatbot/shared/theme.dart';
import 'package:elves_chatbot/state/shellView.dart';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:the_responsive_builder/the_responsive_builder.dart';

class HomeView extends ConsumerWidget {
  const HomeView({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final status = ref.watch(homeStatusProvider);

    return AnimatedSwitcher(
      duration: 300.ms,
      child:   HomeContent(key: ValueKey('content')),
    );
  }
}


class HomeSkeleton extends StatelessWidget {
  const HomeSkeleton({super.key});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const SkeletonBox(height: 26, width: 220).shimmer(),
          const SizedBox(height: 20),
          const SkeletonBox(height: 50).shimmer(),
          const SizedBox(height: 30),
          Row(
            children: const [
              Expanded(child: SkeletonBox(height: 120)),
              SizedBox(width: 12),
              Expanded(child: SkeletonBox(height: 120)),
            ].map((e) => e.shimmer()).toList(),
          )
        ],
      ),
    );
  }
}



class HomeContent extends ConsumerWidget {
 HomeContent({super.key});
  final List<PromptModel> promptList = [
  PromptModel(
    title: 'Midjourney\nPrompt\nGenerator',
    subtitle: 'Generate AI by Kenny',
    onTap: () {
      debugPrint('Midjourney Prompt tapped');
    },
  ),
  PromptModel(
    title: 'Audit Page\nContent for\nSEO [2.1.0]',
    subtitle: 'SEO solution by Florian',
    onTap: () {
      debugPrint('SEO Prompt tapped');
    },
  ),
   PromptModel(
    title: 'Image FX \nPrompt \nGenerator',
    subtitle: 'Generated by Elvis',
    onTap: () {
      debugPrint('SEO Prompt tapped');
    },
   ),];


  final List<ChatModel> ChatList = [
  ChatModel(
    msg: 'What are Some common mistakes to avoid\n when coding a landing Page?'
  ),
   ChatModel(
    msg: 'Home can i ensure that my agency\'s \nbranding is consistent across all platforms?'
  ),
];

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final TextTheme textTheme = Theme.of(context).textTheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
       Padding(
         padding:  EdgeInsets.all(1.h),
         child: Row(
           children: [
             Text(
                'Save Your Time \nWith  Elves  Chat  Bot.', 
                style: textTheme.displayLarge
              ),
             
            const Spacer(),
             
              Container(
                height: 60,
                width: 60,
                decoration: BoxDecoration(
                  color: Colors.white.withOpacity(0.1),
                  shape: BoxShape.circle,
                  border: Border.all(color: AppColors.light, width: 2),
                ),
                child: Icon(
                  Icons.person,
                  color: AppColors.light,
                  size: 30,
                ),
              ).animate().fadeIn().slideX(begin: 0.2),
           ],
         ).animate().fadeIn(),
       ),
    
    
        
    
    
        Padding(
          padding:  EdgeInsets.all(1.h),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                ' Search Your Prompt',
                style: textTheme.displayMedium?.copyWith(fontSize: 18.sp)
              ),
              SizedBox(height: 1.4.h),
              Row(
                children: [
                  GestureDetector(
                    onTap: () {
                      ref.read(shellViewProvider.notifier).state = ShellView.chat;
                    },
                    child: Container(
                      width: 75.w,
                      height: 54,
                      alignment: Alignment.centerLeft,
                       padding:  EdgeInsets.symmetric(horizontal: 5.w),
                      decoration: BoxDecoration(
                        color: AppColors.accent,
                        borderRadius: BorderRadius.circular(30),
                      ),
                      child:  Text('Search here...', 
                      textAlign: TextAlign.start, style: TextStyle(
                        color: Colors.white,
                        fontSize: 16.sp
                      ),),
                    ),
                  ),
                  
                  SizedBox(width: 4.w),
                  CircleAvatar(
                    backgroundColor: AppColors.accent,
                    radius: 30,
                    child: IconButton(
                      icon: const Icon(Icons.search, color: Colors.white),
                      onPressed: (){},
                    ),
                  )
                ],
              ).animate().slideY(begin: 0.2).fadeIn(),
            ],
          ),
        ),
    
    
    
    
        
    
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            children: [
              RowTitle(textTheme: textTheme, title: 'Popular Prompt'),
              SizedBox(height: 2.5.h),
                  
              SizedBox(
                    height: 26.h,
                    child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemCount: promptList.length,
              itemBuilder: (context, index) {
                  return Padding(
                    padding: EdgeInsets.only(right: 4.w),
                    child: PromptCards(model: promptList[index]),
                  );
              },
                    ),
                  ),
            ],
          ),
        ),

        const SizedBox(height: 10),
     Padding(
       padding: const EdgeInsets.all(8),
       child: Column(
        
         children: [
           RowTitle(textTheme: textTheme, title: 'Recenthly Chats'),
            SizedBox(height: 2.5.h),

            SizedBox(
                    height: 21.h,
                    child: ListView.builder(
              scrollDirection: Axis.vertical,
              itemCount: ChatList.length,
              itemBuilder: (context, index) {
                  return RecentChats(model: ChatList[index]);
              },
                    ),
                  ),

                   Container(
                padding: EdgeInsets.symmetric(horizontal: 30.w, vertical: 2.5.h),
                decoration: BoxDecoration(
                  color: AppColors.light,
                  borderRadius: BorderRadius.circular(40),
                ),
                child: Text(
                  'Create New Chat',
                  style: textTheme.labelMedium?.copyWith(
                    color: AppColors.dark,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
           
         ],
       ),
     ),
    


      ],
    );
  }
}

class RowTitle extends StatelessWidget {
  const RowTitle({
    super.key,
    required this.textTheme, required this.title,
  });

  final TextTheme textTheme;
  final String title;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Text(
          title,
          style: textTheme.displayMedium?.copyWith(fontSize: 20.sp)
        ),
        
        const Spacer(),
        Text(
          ' See All',
          style: textTheme.labelMedium
        ),
      ],
    );
  }
}





class PromptModel {
  final String title;
  final String subtitle;
  final VoidCallback onTap;

  PromptModel({
    required this.title,
    required this.subtitle,
    required this.onTap,
  });
}


class PromptCards extends StatelessWidget {
   const PromptCards({super.key, required this.model});

   final PromptModel model;


  @override
  Widget build(BuildContext context) {
    final TextTheme textTheme = Theme.of(context).textTheme;
    return Container(
      height: 25.h,
      width: 55.w,
      decoration: BoxDecoration(
        color: AppColors.light,
        borderRadius: BorderRadius.circular(30),
      ),

      child: Padding(
        padding: const EdgeInsets.all(10.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              model.title,
              style: textTheme.displayLarge?.copyWith(
                color: AppColors.dark, fontWeight: FontWeight.w600, height: 1.4),
            ),
            
            Text(
              model.subtitle,
              style: textTheme.labelLarge?.copyWith(
                fontSize: 15.sp,
                color: AppColors.dark.withOpacity(0.5),
                fontWeight: FontWeight.bold,
              ),
            ),

            const SizedBox(height: 10),

            GestureDetector(
              onTap: model.onTap,
              child: Container(
                margin: EdgeInsets.only(top: 1.5.h),
                padding: EdgeInsets.symmetric(horizontal: 10.w, vertical: 2.h),
                decoration: BoxDecoration(
                  color: AppColors.accent,
                  borderRadius: BorderRadius.circular(40),
                ),
                child: Text(
                  'Use this Prompt',
                  style: textTheme.labelMedium?.copyWith(
                    
                    color: AppColors.light,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            )
            ]),
      )
  

    );
  }
}






class ChatModel {
  final String msg;


  ChatModel({
    required this.msg,
  });
}


class RecentChats extends StatelessWidget {
  const RecentChats({super.key, required this.model});

  final ChatModel model;
    

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding:  EdgeInsets.only(bottom: 15),
      child: Container(
        height: 8.5.h,
        width: double.infinity,
        decoration: BoxDecoration(
          color: Colors.deepPurple.withOpacity(0.2),
          borderRadius: BorderRadius.circular(40),
        ),
        child: Padding(
          padding: const EdgeInsets.all(14.0),
          child: Row(
            children: [
              Icon(
                Icons.chat_bubble_outline_rounded,
                color: AppColors.light.withOpacity(0.7),
                size: 25,
              ),
          
              SizedBox(width: 4.w),
          
              Text(
                model.msg,
                style: Theme.of(context).textTheme.labelSmall?.copyWith(
                  color: AppColors.light.withOpacity(0.9),
                  fontWeight: FontWeight.w500,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}