import 'dart:convert';
import 'package:http/http.dart' as http;

/// Service for interacting with Google Gemini API
class GeminiService {
  final String apiKey;
  
  GeminiService({required this.apiKey});

  static const String _baseUrl = 
      'https://generativelanguage.googleapis.com/v1beta';
  static const String _model = 'gemini-1.5-flash';

  /// Generates content using Gemini API
  Future<String> generateContent(String userMessage) async {
    final url = Uri.parse(
      '$_baseUrl/models/$_model:generateContent?key=$apiKey'
    );

    final requestBody = {
      'contents': [
        {
          'parts': [
            {'text': userMessage}
          ]
        }
      ],
      'generationConfig': {
        'temperature': 0.7,
        'topK': 40,
        'topP': 0.95,
        'maxOutputTokens': 2048,
      },
      'safetySettings': [
        {
          'category': 'HARM_CATEGORY_HARASSMENT',
          'threshold': 'BLOCK_MEDIUM_AND_ABOVE'
        },
        {
          'category': 'HARM_CATEGORY_HATE_SPEECH',
          'threshold': 'BLOCK_MEDIUM_AND_ABOVE'
        },
      ]
    };

    try {
      final response = await http
          .post(
            url,
            headers: {
              'Content-Type': 'application/json',
            },
            body: jsonEncode(requestBody),
          )
          .timeout(
            const Duration(seconds: 30),
            onTimeout: () {
              throw Exception(
                'Request timeout - Gemini API took too long to respond'
              );
            },
          );

      if (response.statusCode == 200) {
        final jsonResponse = jsonDecode(response.body) as Map<String, dynamic>;
        return _extractTextFromResponse(jsonResponse);
      } else {
        // Parse error response
        final errorBody = response.body;
        Map<String, dynamic>? errorJson;
        
        try {
          errorJson = jsonDecode(errorBody) as Map<String, dynamic>;
        } catch (_) {
          // If JSON parsing fails, use raw body
        }

        if (response.statusCode == 400) {
          throw Exception('Invalid request to Gemini API: $errorBody');
        } else if (response.statusCode == 403) {
          throw Exception('API key invalid or permissions denied');
        } else if (response.statusCode == 429) {
          throw Exception('Rate limit exceeded - please try again later');
        } else {
          throw Exception(
            'Gemini API error (${response.statusCode}): $errorBody'
          );
        }
      }
    } on http.ClientException catch (e) {
      throw Exception('Network error: Unable to reach Gemini API - $e');
    } catch (e) {
      if (e is Exception) rethrow;
      throw Exception('Unexpected error: $e');
    }
  }

  /// Extracts the text response from Gemini's JSON structure
  String _extractTextFromResponse(Map<String, dynamic> response) {
    try {
      final candidates = response['candidates'] as List<dynamic>?;
      
      if (candidates == null || candidates.isEmpty) {
        // Check if blocked by safety settings
        final promptFeedback = response['promptFeedback'] as Map<String, dynamic>?;
        if (promptFeedback != null) {
          final blockReason = promptFeedback['blockReason'] as String?;
          if (blockReason != null) {
            throw Exception('Content blocked by safety filters: $blockReason');
          }
        }
        throw Exception('No response generated by Gemini');
      }

      final firstCandidate = candidates[0] as Map<String, dynamic>;
      
      // Check finish reason
      final finishReason = firstCandidate['finishReason'] as String?;
      if (finishReason == 'SAFETY') {
        throw Exception('Response blocked by safety filters');
      }

      final content = firstCandidate['content'] as Map<String, dynamic>?;
      final parts = content?['parts'] as List<dynamic>?;
      
      if (parts == null || parts.isEmpty) {
        throw Exception('Invalid response structure from Gemini');
      }

      final text = parts[0]['text'] as String?;
      
      if (text == null || text.isEmpty) {
        throw Exception('Empty response from Gemini');
      }

      return text.trim();
      
    } catch (e) {
      if (e is Exception) rethrow;
      throw Exception('Failed to parse Gemini response: $e');
    }
  }
}